### ISSUE TITLE
https://bottlepy.org/ refuses to connect.

### ISSUE THREAD

**Issue by Carreau** [bottlepy/bottlepy.org#14]
This makes any  docs build that rely on intersphinx for bottlepy fails.

From https://downforeveryoneorjustme.com/bottlepy.org?proto=https it's not just me.

**Comment by Carreau** [comment]
I see the ip as 212.47.247.247 (ping works),

And nmap sees the following:
```
$ nmap 212.47.247.247
Starting Nmap 7.95 ( https://nmap.org ) at 2024-11-17 11:25 CET
Nmap scan report for mail.defnull.net (212.47.247.247)
Host is up (0.043s latency).
Not shown: 994 closed tcp ports (conn-refused)
PORT    STATE SERVICE
21/tcp  open  ftp
22/tcp  open  ssh
25/tcp  open  smtp
143/tcp open  imap
587/tcp open  submission
993/tcp open  imaps
```

**Comment by defnull** [comment]
Nginx refused to come up automatically after a restart of the VM. Not sure why, yet. The website should be available now.

**Comment by defnull** [comment]
Still no idea why nginx died without a trace. It started up after the restart, logged its startup loglines, but then disappeared. No errors in logs, no OOM event, nothing. Container runtime also did not restarted it, as it should have. I just restarted the VM again and everything came up as expected.

**Comment by Carreau** [comment]
thanks !
